### ISSUE TITLE
Delete items from the cart.

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/wp-woocommerce-api#22]
At the moment we only can add new items to the cart, however I'm not sure if the current mechanism allow delete items from the cart in case the user wants to remove an element from the cart.

Thank you @Rulox

**Comment by Rulox** [comment]
No you still can't, let me change this issue and I will fix it ASAP. Thank you.

**Comment by mitogh** [comment]
Sounds good 👍

**Comment by Rulox** [comment]
This was merged in #23
